version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - "saturnflyer"
    assignees:
      - "saturnflyer"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "ruby"
    # Allow Dependabot to update the lockfile
    allow:
      - dependency-type: "all"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
